export type FontSize =
  //Heading
  | "header1"
  | "header2"
  | "header3"
  | "header4"
  | "header5"
  | "header6"
  //Body
  | "bodyXLargeBold"
  | "bodyXLargeSemiBold"
  | "bodyXLargeMedium"
  | "bodyXLargeRegular"
  | "bodyLargeBold"
  | "bodyLargeSemiBold"
  | "bodyLargeMedium"
  | "bodyLargeRegular"
  | "bodyBaseBold"
  | "bodyBaseSemiBold"
  | "bodyBaseMedium"
  | "bodyBaseRegular"
  | "bodySmallBold"
  | "bodySmallSemiBold"
  | "bodySmallMedium"
  | "bodySmallRegular"
  | "bodyXSmallBold"
  | "bodyXSmallSemiBold"
  | "bodyXSmallMedium"
  | "bodyXSmallRegular"
  | "bodyXXSmallRegular"
  | "bodyXXSmallMedium"
  | "bodyXXSmallBold"
  | "bodyXXSmallSemiBold";
